name: Android CI

on:
  push:
    branches: [ master, alpha ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - uses: Tlaster/android-sign@v1.2.2
      name: Sign app APK
      with:
        releaseDirectory: |
          app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        output: build/release/signed
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        path: build/release/signed
