name: Release CI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Force fetch Tags
      run: |
        git fetch --tags --force

    - name: Get Tag
      id: var
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Write key
      run: |
        if [ ! -z "${{ secrets.SIGNING_KEY }}" ]; then
          echo STORE_PASSWORD='${{ secrets.KEY_STORE_PASSWORD }}' >> gradle.properties
          echo KEY_ALIAS='${{ secrets.ALIAS }}' >> gradle.properties
          echo KEY_PASSWORD='${{ secrets.KEY_PASSWORD }}' >> gradle.properties
          echo STORE_FILE_PATH='../release.keystore' >> gradle.properties
          echo ${{ secrets.SIGNING_KEY }} | base64 --decode > release.keystore
          git update-index --assume-unchanged gradle.properties
        fi

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        path: app/build/outputs/apk/release/*.apk

    - uses: ericcornelissen/git-tag-annotation-action@v2
      id: tag-data

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body: ${{ steps.tag-data.outputs.git-tag-annotation }} &#x20;
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Upload APK
      uses: csexton/release-asset-action@v2
      with:
        github-token: ${{ secrets.GH_TOKEN }}
        release-url: ${{ steps.create_release.outputs.upload_url }}
        pattern: "app/build/outputs/apk/release/*.apk"

    - name: Release to XPosed Repo
      id: create_xposed_release
      uses: actions/create-release@v1
      with:
        owner: Xposed-Modules-Repo
        repo: one.yufz.hmspush
        tag_name: release
        release_name: ${{ github.ref }}
        body: ${{ steps.tag-data.outputs.git-tag-annotation }} &#x20;
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Upload APK
      uses: csexton/release-asset-action@v2
      with:
        github-token: ${{ secrets.GH_TOKEN }}
        release-url: ${{ steps.create_xposed_release.outputs.upload_url }}
        pattern: "app/build/outputs/apk/release/*.apk"
        asset_content_type: application/zip
