name: Release CI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Force fetch Tags
      run: |
        git fetch --tags --force

    - name: Get Tag
      id: var
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - uses: r0adkll/sign-android-release@v1
      name: Sign app APK
      id: sign_apk
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: "30.0.2"

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        path: ${{steps.sign_apk.outputs.signedReleaseFile}}

    - uses: ericcornelissen/git-tag-annotation-action@v2
      id: tag-data

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body: ${{ steps.tag-data.outputs.git-tag-annotation }} &#x20;
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Upload APK
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ steps.sign_apk.outputs.signedReleaseFile }}
        asset_name: HMSPush-${{ steps.var.outputs.tag }}.apk
        asset_content_type: application/zip
